### ISSUE TITLE
Better guess SILE's Lua Version

### ISSUE THREAD

**Issue by Omikhleia** [Omikhleia/awesome-sile-books#18]
```
$ sile -q -e 'print(SILE.lua_version); os.exit()'
5.1
```

_Originally posted by @alerque in https://github.com/Omikhleia/awesome-sile-books/pull/13#discussion_r1739915034_

**Comment by Omikhleia** [comment]
And https://github.com/Omikhleia/awesome-sile-books/pull/13#discussion_r1739925498

**Comment by alerque** [comment]
The `SILE.lua_version` thing has been around since v0.10.10, but the quiet flag didn't get added until v0.14.9 which makes it much easier to reach for. In v0.15+ the flags can be compressed `-qe`, but that doesn't help you if you're potentially querying v0.14 with the same commands.

I'm considering adding some flag or subcommand (`sile lua ...`?)  that would assume no input document and just run Lua stuff without needing the `os.exit()` at the end to terminate before trying to go on to a document. Not just for this little Lua version trick of course, but I find myself querying a number of things from inside SILE other than while rendering documents.
